### ISSUE TITLE
Generation the Helmholz Table

### ISSUE THREAD

**Issue by Carlson-J** [msbc/helmeos#1]
It is not clear in your documentation on how to generate the table you are interpolating over. If I want to make a table that has the true values (or as close as I can get numerically) how would I do that?

**Comment by msbc** [comment]
Unfortunately, I've never made the table and the code provided here is not capable of generating the table itself. I can point you to the webpage of the original Fortran code that interpolates the table http://cococubed.asu.edu/code_pages/eos.shtml and the paper describing the method is here: https://iopscience.iop.org/article/10.1086/313271/pdf

**Comment by Carlson-J** [comment]
Ok, thank you.
